### ISSUE TITLE
建议在程序启动时自动设置SELinux

### ISSUE THREAD

**Issue by G2159687** [ryuunoakaihitomi/ForceCloseLogcat#1]
在5.0以上的系统，日志的获取经常会由于SELinux的干预而失败。我自己刚开始试了好几次，都无法感知到崩溃日志，后来意识到是这个问题。我搜索了一下，发现这个程序里并没有更改SELinux的相关代码，所以推荐增加。

终端上使SELinux变为许可的方法是：
setenforce 0
作者可以考虑一下在程序启动时就执行一下这个命令，这样能大大增加截获日志的几率。

**Comment by ryuunoakaihitomi** [comment]
这个。。。我在lineageos上没发现这个问题，selinux在执行中状态也能正常截取。请回复一下你的运行环境，我看看在其它机器中能否复现。

**Comment by G2159687** [comment]
Cyanogenmod 13.0, Google Nexus 5

授权管理为SuperSU 2.65 Pro, Xposed v87, 无busybox和Magisk。

具体情况为在不修改SELinux的情况下虽然显示服务正在运行，但是截取不到任何报告，但在更改SELinux之后会相继收到报告。在更改SELinux状态之后使用其他系统日志查询软件似乎看到了日志查询过程被SELinux拦截的情况。

**Comment by ryuunoakaihitomi** [comment]
。。。。cm13我也用过，不过也没发现这个问题，一切正常，似乎logcat的运作和selinux的状态根本就没什么关系。。。。好吧，下一个版本将加入这个功能。

**Comment by ryuunoakaihitomi** [comment]
由于此功能会让谷歌安全检测出问题，不再添加此功能。
